[[headers]]
    for = "/*.jpg"
    [headers.values]
        Access-Control-Allow-Origin = "https://alex-arango47.github.io"

[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"
